export const PARTIS: Record<string, string[]> = {
  galley: [
    'SYD',
    'KULL varmt',
    'KULL koldt',
    'Konditor',
    'Besætning',
    'Opsætter',
    'Skagerak',
    'Stilling 2',
    'Stilling 1',
    'Slagter',
  ],
  pearl: [
    'SYD',
    'KULL varmt',
    'KULL koldt',
    'Konditor',
    'Besætning',
    'Opsætter',
    'Skagerak',
    'Stilling 2',
    'Stilling 1',
    'Slagter',
  ],
  shop: [
  'Tøj',
  'Sprut',
  'Slik',
  'Parfume',
  ],
}
